// Builds supabase/seed_real_clubs.sql and supabase/seed_real_demo.sql from data/clubs.json.
//   node scripts/build-seed.mjs
// Re-run `node scripts/scrape-clubs.mjs` first if you want fresh content from the club websites.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { clubs } = JSON.parse(readFileSync(join(root, "data/clubs.json"), "utf8"));

const q = (v) => (v == null || v === "" ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const logoUrl = (c) => (c.logo ? `/logos/${c.slug}.${c.logo.split(".").pop()}` : null);

/* ----------------------------------------------------------- real clubs */

const PLACEHOLDERS = [
  "coding-club", "robotics-club", "ai-ml-club", "cybersec-club", "electronics-club", "gdsc-club", "drama-club",
  "music-club", "dance-club", "literary-club", "photography-club", "film-club", "art-club", "sports-club",
  "chess-club", "nss-club", "eco-club", "entrepreneur-cell", "finance-club", "quiz-club",
];

const clubRows = clubs.map((c) =>
  `(${[c.slug, c.name, c.category, c.tagline, c.description, logoUrl(c), c.accent, c.website, c.instagram, c.linkedin, c.faculty]
    .map(q).join(", ")}, ${c.founded ?? "null"})`,
);

const clubsSql = `-- GENERATED by scripts/build-seed.mjs from data/clubs.json — do not edit by hand.
-- The ${clubs.length} real NHCE co-curricular clubs (content scraped from newhorizonindia.edu/co-curricular).
-- Safe to re-run: existing clubs are updated in place, so lead assignments and events survive.
-- Run AFTER schema.sql.

-- 1. Remove the 20 generic starter clubs from the old seed (cascades to anything attached to them).
delete from public.clubs where slug in (${PLACEHOLDERS.map(q).join(", ")});

-- 2. Insert / refresh the real clubs.
insert into public.clubs (slug, name, category, tagline, description, logo_url, accent_color, website_url, instagram_url, linkedin_url, faculty_advisor, founded_year)
values
${clubRows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name, category = excluded.category, tagline = excluded.tagline, description = excluded.description,
  logo_url = excluded.logo_url, accent_color = excluded.accent_color, website_url = excluded.website_url,
  instagram_url = excluded.instagram_url, linkedin_url = excluded.linkedin_url,
  faculty_advisor = coalesce(excluded.faculty_advisor, public.clubs.faculty_advisor),
  founded_year = coalesce(excluded.founded_year, public.clubs.founded_year),
  is_active = true;
`;
writeFileSync(join(root, "supabase/seed_real_clubs.sql"), clubsSql);

/* ----------------------------------------------------------- simulation */

// Real events keep their real names and (approximate) dates. Clubs whose site lists no events get a
// believable programme built from what the club says it does, spread over the last year plus one upcoming.
const specs = clubs.map((c) => {
  const events = (c.events ?? []).map((e) => ({
    title: e.title, description: e.description, category: e.category, venue: e.venue, starts: e.starts,
    hours: e.hours, capacity: e.capacity, regs: e.regs, budget: e.budget, real: true,
  }));
  const programs = c.programs ?? [];
  programs.forEach((p, i) => {
    const upcoming = i === programs.length - 1 && !(c.events ?? []).length;
    events.push({
      title: p.title, description: p.description, category: p.category, venue: p.category === "Social" ? "NHCE Campus" : `Seminar Hall ${1 + (i % 3)}`,
      offset_days: upcoming ? 9 + (c.slug.length % 20) : -Math.round(25 + (i * 320) / Math.max(programs.length, 1) + (c.slug.length % 7) * 3),
      hours: 3, capacity: 60 + ((i * 20 + c.slug.length) % 60), real: false,
    });
  });
  return {
    slug: c.slug, pop: c.popularity ?? 1, events, team: c.team ?? [], announcements: c.announcements ?? [],
  };
});

const demoSql = `-- GENERATED by scripts/build-seed.mjs from data/clubs.json — do not edit by hand.
-- Simulation on top of the real clubs: their real events (where the websites list any), real student-council rosters,
-- announcements, plus simulated sign-ups / attendance / feedback so every dashboard has data.
--   * Real events: names and descriptions come from the club websites; dates are approximated from the semester labels.
--   * Other programmes follow each club's stated functions; participants, attendance and ratings are simulated.
-- Run AFTER schema.sql, event_ops.sql and seed_real_clubs.sql. Safe to re-run (it replaces what it created).
-- Remove everything:  delete from public.events where club_id in (select id from public.clubs where logo_url like '/logos/%' or slug = 'emsys');
do $seed$
declare
  spec jsonb := $json$${JSON.stringify(specs)}$json$;
  c jsonb; e jsonb; m jsonb; a jsonb;
  v_club uuid; v_event uuid; v_start timestamptz; v_end timestamptz; v_cap int; v_regs int; v_budget numeric; v_rate numeric;
  firsts text[] := array['Aarav','Diya','Vihaan','Ananya','Aditya','Isha','Rohan','Meera','Kabir','Saanvi','Arjun','Priya','Karthik','Neha','Rahul','Sneha','Siddharth','Kavya','Varun','Pooja','Harsha','Divya','Nikhil','Aishwarya','Sai','Lakshmi','Manoj','Shreya','Tanvi','Yash','Bhavana','Chetan','Deepika','Ganesh','Ishaan','Jahnavi','Kiran','Madhuri','Naveen','Rhea'];
  lasts  text[] := array['Sharma','Patel','Reddy','Iyer','Nair','Gupta','Singh','Das','Menon','Rao','Kulkarni','Joshi','Mehta','Bose','Pillai','Hegde','Shetty','Gowda','Naidu','Bhat','Kamath','Prasad','Verma','Jain','Khan','Fernandes','Murthy','Acharya','Srinivasan','Krishnan'];
  depts  text[] := array['CSE','ISE','AIML','ECE','EEE','MECH','CIVIL','AI&DS'];
  codes  text[] := array['CS','IS','AI','EC','EE','ME','CV','AD'];
  comments text[] := array['Great session!','Very useful, learned a lot.','Could have been better organised.','Loved the hands-on part.','More such events please.','Speakers were excellent.','A bit rushed but fun.','Well run and on time.'];
begin
  for c in select * from jsonb_array_elements(spec) loop
    select id into v_club from public.clubs where slug = c->>'slug';
    if v_club is null then
      raise notice 'Club % not found — run seed_real_clubs.sql first', c->>'slug';
      continue;
    end if;

    -- events
    for e in select * from jsonb_array_elements(c->'events') loop
      delete from public.events where club_id = v_club and title = e->>'title';
      v_start := coalesce((e->>'starts')::timestamptz, date_trunc('hour', now()) + ((e->>'offset_days')::int || ' days')::interval + interval '10 hours');
      v_end := v_start + ((e->>'hours')::numeric || ' hours')::interval;
      v_cap := (e->>'capacity')::int;
      v_regs := coalesce((e->>'regs')::int, floor(v_cap * (0.5 + random() * 0.5) * least((c->>'pop')::numeric, 1.2))::int);
      v_budget := coalesce((e->>'budget')::numeric, 2000 + floor(random() * 6000));
      insert into public.events (club_id, title, description, category, venue, starts_at, ends_at, capacity, budget_allocated, budget_spent, status, registration_open)
      values (v_club, e->>'title', e->>'description', e->>'category', e->>'venue', v_start, v_end, v_cap,
              v_budget, case when v_start < now() then round(v_budget * (0.6 + random() * 0.4)) else 0 end, 'published', true)
      returning id into v_event;

      -- sign-ups (the capacity trigger confirms or waitlists them, exactly like real sign-ups)
      insert into public.event_registrations (event_id, full_name, email, roll_no, department, year, phone, registered_at)
      select v_event, p.fn || ' ' || p.ln,
             lower(p.fn || '.' || p.ln || p.g || '@students.nhce.example'),
             '1NH' || lpad((26 - p.yr)::text, 2, '0') || codes[p.d] || lpad((1 + floor(random() * 180))::int::text, 3, '0'),
             depts[p.d], p.yr,
             (array['98','97','99','90','81','63'])[1 + floor(random() * 6)::int] || lpad((floor(random() * 99999999))::bigint::text, 8, '0'),
             least(v_start - interval '2 hours', now()) - random() * interval '14 days'
      from (
        select g,
               firsts[1 + floor(random() * array_length(firsts, 1))::int] as fn,
               lasts[1 + floor(random() * array_length(lasts, 1))::int] as ln,
               1 + floor(random() * 8)::int as d,
               1 + floor(random() * 4)::int as yr
        from generate_series(1, v_regs) g
      ) p
      on conflict do nothing;

      if v_start < now() then
        -- attendance (inserts always start unattended), then feedback from some of those who came
        v_rate := 0.62 + random() * 0.25;
        update public.event_registrations
           set attended = true, attended_at = v_start + random() * interval '40 minutes'
         where event_id = v_event and status = 'confirmed' and random() < v_rate;
        insert into public.event_feedback (event_id, full_name, email, rating, comment)
        select v_event, r.full_name, r.email,
               greatest(1, least(5, round(3.3 + random() * 1.9 + ((c->>'pop')::numeric - 1) * 0.5)::int)),
               case when random() < 0.7 then comments[1 + floor(random() * array_length(comments, 1))::int] end
        from public.event_registrations r
        where r.event_id = v_event and r.attended and random() < 0.55;
      end if;
    end loop;

    -- roster: the real student council (as listed on the club site) plus simulated general members
    delete from public.club_members
     where club_id = v_club
       and (email like '%@students.nhce.example'
            or full_name in (select t->>'name' from jsonb_array_elements(c->'team') t));
    for m in select * from jsonb_array_elements(c->'team') loop
      insert into public.club_members (club_id, full_name, position, status, joined_on)
      values (v_club, m->>'name', m->>'position', 'active', current_date - (200 + floor(random() * 300))::int);
    end loop;
    insert into public.club_members (club_id, full_name, email, roll_no, department, year, position, status, joined_on)
    select v_club, p.fn || ' ' || p.ln, lower(p.fn || '.' || p.ln || p.g || '@students.nhce.example'),
           '1NH' || lpad((26 - p.yr)::text, 2, '0') || codes[p.d] || lpad((1 + floor(random() * 180))::int::text, 3, '0'),
           depts[p.d], p.yr, 'Member', case when random() < 0.12 then 'alumni' else 'active' end,
           current_date - (random() * 700)::int
    from (
      select g,
             firsts[1 + floor(random() * array_length(firsts, 1))::int] as fn,
             lasts[1 + floor(random() * array_length(lasts, 1))::int] as ln,
             1 + floor(random() * 8)::int as d,
             1 + floor(random() * 4)::int as yr
      from generate_series(1, floor((18 + random() * 22) * (c->>'pop')::numeric)::int) g
    ) p;

    -- announcements
    for a in select * from jsonb_array_elements(c->'announcements') loop
      delete from public.announcements where club_id = v_club and title = a->>'title';
      insert into public.announcements (club_id, title, body, pinned)
      values (v_club, a->>'title', a->>'body', coalesce((a->>'pinned')::boolean, false));
    end loop;
  end loop;
end $seed$;
`;
writeFileSync(join(root, "supabase/seed_real_demo.sql"), demoSql);
console.log(`Wrote seed_real_clubs.sql (${clubs.length} clubs) and seed_real_demo.sql (${specs.reduce((n, s) => n + s.events.length, 0)} events).`);
